import type { Metadata } from 'next'
import './globals.css'
import { inter } from './ui/fonts'
import { Footer } from '@/components/layout/footer'
import { ThemeProvider } from '@/components/dark-mode/theme-provider'
import { Header } from '@/components/layout/header'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Ecommerce-edu app - Next.js',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 z-50 bg-white dark:bg-black/60 border-b shadow-sm">
            <Header />
          </header>
          {children}
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
