import type { Metadata } from 'next'
import './globals.css'
import { inter } from './ui/fonts'

export const metadata: Metadata = {
  title: 'Ecommerce-edu app - Next.js',
  description: 'Generated by create next app'
}

// eslint-disable-next-line @typescript-eslint/space-before-function-paren
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
